### PR TITLE
Fix variance

### LINKED ISSUE #3: The variance is wrong
```rust
use std::cell::Cell;
use cell_project::cell_project as cp;

struct Foo<'a> {
    x: Option<&'a Cell<Foo<'a>>>,
}

impl<'a> Drop for Foo<'a> {
    fn drop(&mut self) {
        // `ourselves` is an &Cell<Self>.
        // NB: `Drop` is unsound.
        if let Some(ourselves) = self.x.as_ref() {
            // replace `self` (but this doesn't actually replace `self`)
            let is_x_none = ourselves.replace(Foo {
                x: None,
            }).x.as_ref().is_none();
            // if we just moved out of `self`, and we had a `Some` originally,
            // how come this is a `None`?
            if is_x_none {
                println!("how did we get a None?");
            }
        }
    }
}

fn main() {
    let foo = Cell::new(Foo {
        x: None,
    });
    let x = cp!(Foo<'_>, foo.x);
    x.set(Some(&foo));
}
```

```
$ cargo +nightly miri run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri /tmp/cargo/target/miri/x86_64-unknown-linux-gnu/debug/unsound_cell_project`
error: Undefined Behavior: not granting access to tag <untagged> because incompatible item is protected: [Unique for <2472> (call 796)]
   --> /home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:404:31
    |
404 |         mem::replace(unsafe { &mut *self.value.get() }, val)
    |                               ^^^^^^^^^^^^^^^^^^^^^^ not granting access to tag <untagged> because incompatible item is protected: [Unique for <2472> (call 796)]
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
            
    = note: inside `std::cell::Cell::<Foo>::replace` at /home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:404:31
note: inside `<Foo as std::ops::Drop>::drop` at src/main.rs:14:29
   --> src/main.rs:14:29
    |
14  |               let is_x_none = ourselves.replace(Foo {
    |  _____________________________^
15  | |                 x: None,
16  | |             }).x.as_ref().is_none();
    | |______________^
    = note: inside `std::ptr::drop_in_place::<Foo> - shim(Some(Foo))` at /home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:486:1
    = note: inside `std::ptr::drop_in_place::<std::cell::UnsafeCell<Foo>> - shim(Some(std::cell::UnsafeCell<Foo>))` at /home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:486:1
    = note: inside `std::ptr::drop_in_place::<std::cell::Cell<Foo>> - shim(Some(std::cell::Cell<Foo>))` at /home/soniex2/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:486:1
note: inside `main` at src/main.rs:32:1
   --> src/main.rs:32:1
    |
32  | }
    | ^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
```

https://users.rust-lang.org/t/cursed-pinned-cells/74928

### PR DESCRIPTION
**Pull request by SoniEx2**
Closes #3

### CODE REVIEW

**Comment by pinkforest** [comment]
Hi @RustyYato is cell-project still maintained - should people be using it ? cheers

**Comment by RustyYato** [comment]
Thanks for the ping @pinkforest .
This slipped under my radar. I'm passively maintaining `cell-project`. This crate should be fine to use.

@SoniEx2 I'm fine with raising MSRV for the fix here. Thanks for the PR

**Comment by SoniEx2** [comment]
We believe this fix does not raise the MSRV. However, it is unclear to us whether it's *fully* sound - specifically, due to provenance, which is an area of unsafe that's still in flux (see also [UCG](https://github.com/rust-lang/unsafe-code-guidelines/issues?q=is%3Aissue+label%3AT-provenance+is%3Aopen+)). Ideally this would be using `addr_of_mut!`, but we do believe the current code goes out of its way to correct for provenance, so it might be okay after all. We don't enough about provenance to be able to tell, tho.

**Comment by RustyYato** [comment]
I'm going to switch to use `addr_of_mut` in the next release and add miri test to CI, so I think that should be fine.
I'm aware of the UCG's discussions on provenance and how much of it is in flux 😄.

**Comment by pinkforest** [comment]
Hi @RustyYato would you like to send advisory on `informational = unsound` PR to RustSec ? thx!

**Comment by RustyYato** [comment]
Done in https://github.com/rustsec/advisory-db/pull/1391

**Pull request merged**
